-유저테이블-
CREATE TABLE "USERS" (
	"USERS_NO"	NUMBER	PRIMARY KEY,
	"USERS_ID"	VARCHAR2(20)	NOT NULL,
	"USERS_PW"	VARCHAR2(200)	NOT NULL,
	"USERS_NAME"	VARCHAR2(20)	NOT NULL,
	"USERS_EMAIL"	VARCHAR2(50)	NOT NULL,
	"USERS_NICK"	VARCHAR2(30)	NOT NULL,
	"USERS_TEL"	CHAR(11)	NOT NULL,
	"USERS_ADDR"	VARCHAR2(500)	NOT NULL,
	"ENROLL_DT"	DATE DEFAULT SYSDATE,
	 "SECESSION_FL"   CHAR(1)   DEFAULT 'N'
);
ALTER TABLE "USERS" 
ADD CONSTRAINTS USERS_S_CHK CHECK(SECESSION_FL IN ('Y','N'));

-강사테이블-
CREATE TABLE "TEACHER" (
	"TEACHER_NO"	NUMBER	PRIMARY KEY,
	"TEACHER_ID"	VARCHAR2(20)	NOT NULL,
	"TEACHER_PW"	VARCHAR2(200)	NOT NULL,
	"TEACHER_NAME"	VARCHAR2(20)	NOT NULL,
	"TEACHER_EMAIL"	VARCHAR2(50)	NOT NULL,
	"TEACHER_TEL"	CHAR(11)	NOT NULL,
	"TEACHER_ADDR"	VARCHAR2(500)	NOT NULL,
	"ENROLL_DT"	DATE	DEFAULT SYSDATE,
	"SECESSION_FL"   CHAR(1)   DEFAULT 'N'
);
ALTER TABLE "TEACHER" 
ADD CONSTRAINTS TEACHER_CHK CHECK(SECESSION_FL IN ('Y','N'));


-강의노트 테이블-
CREATE TABLE "LECTURE_NOTE"(
	"NOTE_NO" NUMBER PRIMARY KEY,
	"NOTE_CONTENT" CLOB NOT NULL,

	"USERS_NO" NUMBER NOT NULL,
	"LECTURE_NO" NUMBER NOT NULL
)




-이메일인증테이블-
CREATE TABLE "CERTIFICATION" (
	"C_EMAIL"	VARCHAR2(50)	PRIMARY KEY,
	"C_NUMBER"	CHAR(6)	NOT NULL,
	"ISSU_DT"	DATE DEFAULT SYSDATE
);

-강의테이블-
CREATE TABLE "LECTURE" (
	"LECTURE_NO"	NUMBER	PRIMARY KEY,
	"LECTURE_NAME"	VARCHAR2(200)	NOT NULL,
	"UPLOAD_DATE"	DATE DEFAULT SYSDATE,
	"VIEW_CNT"	NUMBER	NULL,
	"PRICE"	NUMBER	NOT NULL,
	"TEACHER_NO"	NUMBER	NOT NULL,
	"CATEGORY_NO"	NUMBER	NOT NULL
);

-카테고리테이블- 
CREATE TABLE "CATEGORY" (
	"CATEGORY_NO"	NUMBER	PRIMARY KEY,
	"CATEGORY_NAME"	VARCHAR2(50)	NOT NULL
	
);

-내강의 테이블-
CREATE TABLE "MY_LECTURE" (
	"USERS_NO"	NUMBER	NOT NULL,
	"LECTURE_NO"	NUMBER	NOT NULL,
	"PAY_NO"	NUMBER	NOT NULL
);

-찜목록테이블-
CREATE TABLE "FAV_LEC" (
	"FAV_NO"	NUMBER	PRIMARY KEY,
	"FAV_YN"	CHAR(1) DEFAULT 'N',
	"LECTURE_NO"	NUMBER	NOT NULL,
	"USERS_NO"	NUMBER	NOT NULL
); 

-결제테이블-
CREATE TABLE "PAYMENT" (
	"PAY_NO"	NUMBER	PRIMARY KEY,
	"PAY_WAY"	VARCHAR2(50)	NOT NULL,
	"PAY_DATE"	DATE DEFAULT SYSDATE,
	"PAY_PRICE"	NUMBER	NOT NULL,
	"USERS_NO"	NUMBER	NOT NULL,
	"LECTURE_NO"	NUMBER	NOT NULL
);

-관리자테이블-
CREATE TABLE "MANAGER" (
	"MGR_NO"	NUMBER	PRIMARY KEY,
	"MGR_NAME"	VARCHAR2(50)	NOT NULL,
	"MGR_ID"	VARCHAR2(50)	NOT NULL,
	"MGR_PW"	VARCHAR2(200)	NOT NULL
);

-공지사항테이블-
CREATE TABLE "NOTICE" (
	"NOTICE_NO"	NUMBER	PRIMARY KEY,
	"NOTICE_TITLE"	VARCHAR2(200)	NOT NULL,
	"NOTICE_CONTENT"	CLOB	NOT NULL,
	"NOTICE_DATE"	DATE DEFAULT SYSDATE,
	"MGR_NO"	NUMBER	NOT NULL
);

-시퀀스생성-
CREATE SEQUENCE SEQ_USERSER_NO NOCACHE;
CREATE SEQUENCE SEQ_TEACHER_NO NOCACHE;
CREATE SEQUENCE SEQ_LECTURE_NO NOCACHE;
CREATE SEQUENCE SEQ_CATEGORY_NO NOCACHE;
CREATE SEQUENCE SEQ_FAV_NO NOCACHE;
CREATE SEQUENCE SEQ_PAY_NO NOCACHE;
CREATE SEQUENCE SEQ_MANAGER_NO NOCACHE;
CREATE SEQUENCE SEQ_NOTICE_NO NOCACHE;
COMMIT;



