ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

CREATE USER elearning IDENTIFIED BY 1234;

GRANT CONNECT, RESOURCE TO elearning;


ALTER USER elearning DEFAULT TAbLESPACE SYSTEM QUOTA UNLIMITED ON SYSTEM;